
import 'package:flutter/material.dart';
import 'package:motivational_quotes_app/model.dart';

const QUOTES_CATEGORIES = const [
  Category(id: "1",
    title: "“Learn as if you will live forever, live like you will die tomorrow.” — Mahatma Gandhi",
    color: Colors.blue,
  ),
  Category(id: "2",
    title: "“Tough times don't last, tough people do“ Unknown",
    color: Colors.lightBlue,
  ),
  Category(id: "3",
    title: "“Don’t let yesterday take up too much of today.” — Will Rogers",
    color: Colors.green,
  ),
  Category(id: "4",
    title: "“Goal setting is the secret to a compelling future.” — Tony Robbins",
    color: Colors.blueGrey,
  ),
  Category(id: "5",
    title: "“Women challenge the status quo because we are never it.” — Cindy Gallop",
    color: Colors.teal,
  ),
  Category(id: "6",
    title: "“Either you run the day or the day runs you.” — Jim Rohn",
    color: Colors.orange,
  ),
  Category(id: "7",
    title: "“When you change your thoughts, remember to also change your world.”—Norman Vincent Peale",
    color: Colors.yellow,
  ),
  Category(id: "8",
    title: "“Success usually comes to those who are too busy looking for it.” — Henry David Thoreau",
    color: Colors.cyan,
  ),

  Category(id: "9",
    title: "“Learn as if you will live forever, live like you will die tomorrow.” — Mahatma Gandhi",
    color: Colors.purple,
  ),
  Category(id: "10",
    title: "“Tough times don't last, tough people do“ Unknown",
    color: Colors.pink,
  ),
  Category(id: "11",
    title: "“Don’t let yesterday take up too much of today.” — Will Rogers",
    color: Colors.lime,
  ),
  Category(id: "12",
    title: "“Goal setting is the secret to a compelling future.” — Tony Robbins",
    color: Colors.blueGrey,
  ),
  Category(id: "13",
    title: "“Women challenge the status quo because we are never it.” — Cindy Gallop",
    color: Colors.teal,
  ),
  Category(id: "14",
    title: "“Either you run the day or the day runs you.” — Jim Rohn",
    color: Colors.orange,
  ),
  Category(id: "15",
    title: "“When you change your thoughts, remember to also change your world.”—Norman Vincent Peale",
    color: Colors.yellow,
  ),
  Category(id: "16",
    title: "“Success usually comes to those who are too busy looking for it.” — Henry David Thoreau",
    color: Colors.cyan,
  ),
];